### ISSUE TITLE
push option is not woking 

### ISSUE THREAD

**Issue by rmney** [JCluzet/42_EXAM#1]

**Comment by JCluzet** [comment]
Hi 👋🏼 
What is not working ?
Can you send a screenshot ?
Thanks.

**Comment by rmney** [comment]
<img width="724" alt="Screen Shot 2021-07-11 at 22 04 27" src="https://user-images.githubusercontent.com/55449742/125209880-f7c6c180-e293-11eb-89a4-deb03488c1f1.png">

but when i type it followed by the command time it works

**Comment by JCluzet** [comment]
it's now fix with readline added

**Comment by ma-hacker** [comment]
hi sir please how to push my projects on folder rendu
please help me

**Comment by JCluzet** [comment]
Hi @ma-hacker 
When you encounter a new problem with 42_EXAM you have to open a new issue.
As mentioned several times in the topic and in the explanations of the exam, here you don't need to use GIT, so you don't need to add/commit/push your projects.
Once you have completed the exercise you can simply type in the `grademe` command to be corrected.
