### ISSUE TITLE
Permission error running a.out

### ISSUE THREAD

**Issue by alessandracruz** [JCluzet/42_EXAM#11]
When a tried de option 3, the compilation of 42_EXAM v2.1 give me this error. Can you help me?

- Your OS: Linux acruz-VirtualBox 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
      - The error message:
In file included from .system/exercice.cpp:1:
.system/exam.hpp:8:10: fatal error: readline/readline.h: Arquivo ou diretório inexistente
    8 | #include <readline/readline.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Thanks for your contribution !
bash: linha 183: ((: == 4: erro de sintaxe: esperava operando (token de erro é "== 4")
bash: linha 227: ((: == 5: erro de sintaxe: esperava operando (token de erro é "== 5")
bash: linha 241: ((: == 6: erro de sintaxe: esperava operando (token de erro é "== 6")

**Comment by JCluzet** [comment]
Hello Alessandracruz 👋

First, thanks you for using 42_EXAM.
42_EXAM uses a single external package to manage the prompt, you will see more details about this package with the Minishell project for example. 

The readline package is well known and already pre-installed on all MacOS and most Linux. 
However this one may not be installed on some OS, like Kali Linux or others.

To install it you just have to type :
`sudo apt-get install libreadline-dev`

However, I have just pushed a **_new version_** of 42_EXAM which checks automatically if readline is installed, and if it is not the case it is now installed automatically ! 

You just have to use `make re` to install readline automatically.

Good luck for your exams!

**Comment by alessandracruz** [comment]
Thank you for your help, JCluzet!
I deleted previously created 42-EXAM folder and installed the readline package.
After that, I went into the 42-EXAM folder and ran `make re`, but I don't have permission.

I repeated the process and the error is now another. 

I will put below the error that I have found. Can you help-me again?

Compilation of 42_EXAM v2.1 /

Done!
.system/launch.sh: linha 96: ./a.out: Permissão negada
make: *** [Makefile:15: all] Erro 126

42-EXAM 

Launch and check update... bash: linha 137: cd: 42-EXAM: Arquivo ou diretório inexistente
.system/launch.sh: linha 3: ./.system/a.out: Permissão negada
bash: linha 183: ((: == 4: erro de sintaxe: esperava operando (token de erro é "== 4")
bash: linha 227: ((: == 5: erro de sintaxe: esperava operando (token de erro é "== 5")
bash: linha 241: ((: == 6: erro de sintaxe: esperava operando (token de erro é "== 6")

![WhatsApp Image 2022-09-16 at 12 06 21](https://user-images.githubusercontent.com/66642733/190712900-7260982d-5cf8-42f2-876b-c0dc83e80b67.jpeg)

**Comment by JCluzet** [comment]
Ok indeed this error is not normal.
It should be able to be fixed with a `sudo make re`, but I would like to be able to fix it for all the people in the same case as you without using sudo.

I just pushed a new version, could you test by trying again?
You can try by deleting the 42-EXAM folder and using the Grademe command (`bash -c "$(curl https://grademe.fr)"`) to reinstall it. 
If after that you still get the same right error please tell me with the new message.

Thanks again for your comments which will surely help other students in your case.

**Comment by alessandracruz** [comment]
It works! Thanks so much!

When I finalize an exam issue to push, do I need to configure anything in my Github?

Because I got this message when I tried to push:

Username for 'https://github.com': alessandracruz
Password for 'https://alessandracruz@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/JCluzet/42_EXAM.git/'

**Comment by JCluzet** [comment]
No, not at all, as mentioned in the explanations before the exam and status there is no need to use git to get corrected during the exam. 
You only need to do the exercise in the right folder and then you can immediately type "`grademe`" in the 42_EXAM prompt. 
This is the only difference with the real ExamShell of 42.

**Comment by alessandracruz** [comment]
Wow, thank you so much!
I read that, but I didn't pay attention!
Everything is working here now.
You were amazing!
Now let's study!

Look:

Mode: REAL | Current Grade: 25 / 100

  Level 0: 
    0: ft_strcpy for 25 potential points (Success)
  Level 1: 
    0: max for 50 potential points (Current)

Assignement: max for 50xp, try: 0

Subject location:  ~/42-EXAM/subjects/subject.en.txt
Exercice location: ~/42-EXAM/rendu/max/
Here you don't need to use git.

End date: 16/09/2022 20:39:23
Left time: 2hrs, 24min and 14sec

==================================================================
Use the "grademe" command to be graded, or "help" to get some help.
examshell> 

THANK YOU!

**Comment by JCluzet** [comment]
You're welcome
Congrats on your ft_strcpy! 

ps : As soon as you pass an exercise or an exam you can see your login on the Grademe.fr website to congratulate you ;)

If you have other questions, don't hesitate.
