### ISSUE TITLE
Install readline on WSL

### ISSUE THREAD

**Issue by mohsinhdr** [JCluzet/42_EXAM#118]
Check if libreadline-dev is installed
Please install it manually or write an Issue on Github...
make: *** [Makefile:14: all] Error 1

**Comment by JCluzet** [comment]
Hey @mohsinhdr 
What is your os system?
MacOS, Ubuntu, WSL ?

**Comment by mohsinhdr** [comment]
Wsl

**Comment by JCluzet** [comment]
When you do `sudo apt update` and `sudo apt install libreadline-dev` it’s working? if not please send me the output of the command

**Comment by mohsinhdr** [comment]
Yes, it is working. Thanks matee
