### ISSUE TITLE
at final exercise success, repertory is not moved to 'success' repertory

### ISSUE THREAD

**Issue by xDeadpoolx** [JCluzet/42_EXAM#12]
Hi,

while taking rank 02 exam, I oberved twice that upon finishing (successfully) the last exercise (#4), the repertory which is in 'rendu' is not moved to "success" as are the previous ones.

**Comment by JCluzet** [comment]
Damn! 
After checking, you were right, I just fixed the problem in the last push.
If you have any other problems don't hesitate.

Good luck for your exams!
