### ISSUE TITLE
Issue with subject

### ISSUE THREAD

**Issue by vkatasonov** [JCluzet/42_EXAM#121]
Hello, I don't know what's going on, but subjects folder became empty after the first test passed. 

<img width="1273" alt="Screenshot 2023-08-31 at 17 20 20" src="https://github.com/JCluzet/42_EXAM/assets/965086/128692da-4988-4087-bc90-5256d7d26b1d">

**Comment by JCluzet** [comment]
Hey @vkatasonov 👋

In a Linux or Unix-like operating system, the terminal maintains a file descriptor pointing to the current directory. 
If a file is deleted and recreated (subject.en.fr) while you're in that directory, the terminal may still point to the old file descriptor. 

As a result, changes may not be immediately visible. To refresh this, you usually need to leave the directory and come back, so the shell updates its internal pointers.
