### ISSUE TITLE
student/rank2/union

### ISSUE THREAD

**Issue by marcell114** [JCluzet/42_EXAM#155]
➜  ~ cat ~/42-EXAM/subjects/subject.en.txt
cat: /home/marcell/42-EXAM/subjects/subject.en.txt: No such file or directory

subject for the "union" exercise is missing. First i thought, that I messed up something because i made a typo on command line. Then just exit to program. Now I got the same exercise and its actually really missing.
![Screenshot from 2024-01-23 17-16-33](https://github.com/JCluzet/42_EXAM/assets/96981873/ed83b8e5-f25d-4074-86a4-3a483658b552)

**Comment by JCluzet** [comment]
Hey @marcell114 👋

Union is no longer in the 42 exam subjects. 
It was removed from 42_EXAM 6 months ago. 
Did you update it? 
If not, delete the repo and reclone it.

**Comment by JCluzet** [comment]
see #83 & #81

**Comment by marcell114** [comment]
@JCluzet I started to use this just about a month ago max 2. So its should be the updated version. 
But thanks :) i will try to updated if still remains i can live with. Thank you!

**Comment by JCluzet** [comment]
You can keep me posted here if that doesn't solve your problem.
Github's automatic update system isn't great, I'll have to rework it some day.
