### ISSUE TITLE
Bypass the correction system

### ISSUE THREAD

**Issue by theblack-wis** [JCluzet/42_EXAM#16]
Hey i dont know exactly if this error in your script (grademe) or in 42 network but for thr function that require re-creation like (ft_atoi, ft_strlen ...) 
you can just include the lib and renamed it using preprocessing like :
define strc as strlen and use strc directly in your c file "
`{
   return strc(str);
}`

and this will graded as a successfully code (in your grademe script but i dont know about 42)

![Image-2022](https://user-images.githubusercontent.com/70611244/192907746-ab8497f5-8ef7-42ab-9c11-98c3f6f9e0fe.jpeg)

**Comment by JCluzet** [comment]
Hi theblack-wis 👋

You're right, on 42_EXAM you can cheat by adding directly the library in the exercise, in this case your exercise will be validated.

At 42 there is obviously a verification of this kind of things, besides you risk a -42 by trying it.

My program is only made to train you, you can cheat but it won't really help you to pass the exam at 42, that's also why there are cheat commands on my program which allow you to automatically validate your exercise `force_success`, or to remove the time between each try `remove_grade_time`.

I thought about introducing a system that checks that you don't put a library to use this kind of technique, but it's not interesting, 42_EXAM was created to train you, you can always bypass the system, and it's not 100% reliable. 

Good luck for your exams :)

**Comment by theblack-wis** [comment]
If this error is present in 42 as well, then this is a problem that must be reported. It is not about cheating, but about risking.

**Comment by JCluzet** [comment]
42 has a better and more reliable examination system than 42_EXAM, in no case it is possible to do this in ExamShell at 42, the exercise will be FAIL, for sure. 
In addition to that you risk getting a score of -42.
