### ISSUE TITLE
suppression of previous exercise choice

### ISSUE THREAD

**Issue by Alafff** [JCluzet/42_EXAM#17]
Hello there!

Just asking if it would be possible to keep the previous exercises done in the rendu repertory when you validate them.

Cause for exam 5 as you need the 00 to do the 01 and the 01 to do the 02 , it's becoming tedious real fast to remake them each time :)

**Comment by JCluzet** [comment]
Hi Alafff 👋

Thanks for your comment.
Until now the successful exercises were moved to the `success/` folder.
However, you are right, this is not the behaviour of the ExamShell at 42.

I have just modified and pushed a new version that leaves the previous exercises in the rendered folder as long as the exam is not finished.
If you have any other questions don't hesitate.
