### ISSUE TITLE
site hs

### ISSUE THREAD

**Issue by FOXEST57** [JCluzet/42_EXAM#173]
Bonjour votre site est HS impossible de se connecter

**Comment by JCluzet** [comment]
Bonjour, le site Grademe.fr ? Quel erreur avez vous ?

**Comment by FOXEST57** [comment]
Bonjour c'est bon maintenant il y avait 404 merci Envoyé de mon iPhoneLe 24 juil. 2024 à 09:52, JCluzet ***@***.***> a écrit :﻿
Bonjour, le site Grademe.fr ? Quel erreur avez vous ?
