### ISSUE TITLE
Thank you for your work on Grademe

### ISSUE THREAD

**Issue by Rsilva89snake** [JCluzet/42_EXAM#181]
Hello JCluzet,

I’d like to express my sincere thanks for the excellent work you’ve done with Grademe. I am currently taking part in the 42 Porto Piscine, and your project has been a great help throughout the process. I’ve been tracking my progress on my GitHub, and all exercises that are available for 42 students.

There’s only one week left for me to finish the Piscine here in Portugal. Although I would love to sponsor your project but i'm facing some financial challenges at the moment, I’m incredibly grateful for the support your project has provided. I chose 42 with the goal of improving my job opportunities or even starting my own project in the future.

Speaking of which, I have an idea for a vending machine project that could use AI to prevent vandalism and fraud, as well as offer contactless payment options like NFC, MB Way, Apple Pay, Google Pay, etc.

I would love to sponsor your project when my financial situation improves. Thank you again for your hard work and dedication!

Best regards,
Rui Silva

**Comment by JCluzet** [comment]
Hey @Rsilva89snake 

Wow, thank you so much for your message!
It really warms my heart, and I’m super happy to know that the project has been so helpful to you. No worries at all if you’re unable to sponsor, that’s totally understandable. 

If you want, you can send me an email at jo@cluzet.fr with your login from `echo $USER`, and I’ll add you as a VIP in the program. 
Also, congratulations on your future ideas – I wish you all the best and good luck with the rest of your exams!

Friendly, 

Jo
