### ISSUE TITLE
Missing ft_strpbrk

### ISSUE THREAD

**Issue by Welepy-dev** [JCluzet/42_EXAM#183]

**Comment by JCluzet** [comment]
Hello @Welepy-dev 👋
Indeed several 42 subjects are not yet in 42_EXAM 
The subjects can change from one day to the next, however, the community can add exercises, and you can easily do it yourself! You will also earn VIP status for free. 

All the explanations on how to add an exercise to grademe are here: [Contribution by adding exercices](https://github.com/JCluzet/42_EXAM/blob/main/CONTRIBUTING.md)

I’m closing this issue as it doesn’t correspond to a problem, but I invite you to create a pull request with the exercise in question so I can review it 😃

Thanks and happy studying ! 📚

**Comment by Welepy-dev** [comment]
Oh, thanks for the quick response, I will work now on adding the missing exercises.
