### ISSUE TITLE
exam rank 04 fail

### ISSUE THREAD

**Issue by MAROUAN17** [JCluzet/42_EXAM#184]
i don't know why my microshell keep failing
am I missing something ?
thanks for help!
[microshell.txt](https://github.com/user-attachments/files/17531139/microshell.txt)
[trace.txt](https://github.com/user-attachments/files/17531297/trace.txt)

**Comment by baringuney** [comment]
I have exactly the same problem. It fails even though all traces are the same.

**Comment by MAROUAN17** [comment]
Hello, there are just some missing protections in my code. It works after fixing it! Try checking your system calls.

**Comment by baringuney** [comment]
Can you upload the final code. I don't think i have any missing protection and i am still failing.
