### ISSUE TITLE
Probleme makefile sur WSL

### ISSUE THREAD

**Issue by julesmuntz** [JCluzet/42_EXAM#2]
**_-r_** manquant ligne 20.
Le programme se lance parfaitement depuis.

**Comment by JCluzet** [comment]
Yo ! 
Whaw quel erreur de dinguo d'oublier le -r pour copier un directory, merci je l'ai rajouté.
Étrangement ça fonctionnait de mon coté je n'ai jamais rencontré d'erreur sur MacOS 12.+, ça doit venir des spécificités de ton OS... Sur quel OS exécutes tu 42_EXAM ?

**Comment by julesmuntz** [comment]
Cool alors! Super programme en tout cas, merci d'avoir eu l'initiative de le proposer. En OS, j'utilise WSL pour utiliser Ubuntu 20.04 sur le "Windows Terminal" car je suis un disciple de Windows😅

**Comment by JCluzet** [comment]
Oh c'est pour ça, j'ai codé le projet entièrement pour MacOS, assez dingue que tu arrives a le lancer sur WSL!
Tu risques de rencontrer des soucis dans la correction également, a part si WSL prend tout en charge.
Bon exam 😉

**Comment by julesmuntz** [comment]
Merci! Oui j'ai assez galéré avant d'avoir la configuration la plus fidèle à un OS physique. Le seul truc que j'ai pas réussi à faire, c'est pouvoir lancer des programmes qui agissent sur le réseau. Dans ce cas j'utilise VirtualBox.
