### ISSUE TITLE
No grading script present for `ft_printf` excercise

### ISSUE THREAD

**Issue by Kolterdyx** [JCluzet/42_EXAM#20]
There is no grading script for the excercise `ft_printf`, in the student exam 03

**Comment by JCluzet** [comment]
Hello Kolterdyx!
Indeed since my last push a big error was added which prevented to correct any exercise after Level 0.
And the subject was also not displayed.
Sorry for this big mistake on my side, everything is fixed!
Let me know if you find a new problem.

Have a good exam!
