### ISSUE TITLE
Correction of the ExamRank06 may not work as expected.

### ISSUE THREAD

**Issue by JCluzet** [JCluzet/42_EXAM#24]
It has been observed that the ExamRank06 correction MAY indicate an exam as wrong when it is right, or run in an infinite loop on Linux.
We are currently looking for a solution or a new way to correct the exam.

**Comment by Kek5chen** [comment]
could it be that this got fixed by #43 ? I definitely fixed some things for linux and exactly something similar to what is described here

**Comment by JCluzet** [comment]
OH yeah! 
This is indeed fixed, thanks again to you!
