### ISSUE TITLE
Can't auto-install lib readline on Linux

### ISSUE THREAD

**Issue by LohanGuedes** [JCluzet/42_EXAM#25]
When trying to use The script under a Linux operating system the script ALWAYS ask for the ReadLine lib. Even when it's installed.
https://i.imgur.com/aDF2Ohq.png

OS:
Fedora 36 - Stable release

![image](https://user-images.githubusercontent.com/61142917/203296972-d55433c2-9029-4435-a0df-4b0317756dda.png)

![image](https://user-images.githubusercontent.com/61142917/203297227-b38bf240-0715-417d-a19a-5e44d8caf31b.png)

**Comment by JCluzet** [comment]
Hi, 
Do you still have this problem?
If not you can close the issue

**Comment by LohanGuedes** [comment]
@JCluzet  Thanks for the help! indeed I  was missing the readline function. It was already installed via DNF, but unfortunately it only worked if installed via `yum`.

I'm also sorry for the long response time. Couldn't find the issue that I opened because I'm not that used to github. I'm sorry.

So the fix was:

`sudo yum install readline`

Also thanks for changing the name of the issue, I need to get better at this too. <3

**Comment by JCluzet** [comment]
Thank you for your feedback, thanks to this I just pushed a **new version** that will try to install readline with `yum` if it does not work with `apt-get`.
This will surely help other people in your case.

If you have any other question don't hesitate to open a new issue.

Thanks for your star ;) and good exams!
