### ISSUE TITLE
42_EXAM can’t find my exercice file 

### ISSUE THREAD

**Issue by alessandracruz** [JCluzet/42_EXAM#28]
Hello! How are you? I don't know what is happening with grademe in the exam simulation, can you help me? I checked if everything is right in the folder and the function is there and made the same way as in the repository, but it gives FAILURE.

![Terminal](https://user-images.githubusercontent.com/66642733/205405604-5bb5d3db-caa6-4db1-a91c-5d665b6a7581.png)

**Comment by JCluzet** [comment]
Hi! 
I'm doing great thanks :)

You did not put your exercise in the right folder.
You have to create a folder `ft_strlen/` in the folder `rendu/` , then in the folder `ft_strlen/` put your exercise `ft_strlen.c`
That's how it is in the real 42 exam. 
Let me know if you still have a problem after that.

Have a good exam ;)

**Comment by alessandracruz** [comment]
Oops...you're right! I forgot to create the function folder! SUCCESS now!
Thanks for the help!

**Comment by JCluzet** [comment]
don't hesitate to recreate an Issue if you have a new problem ;)

**Comment by alessandracruz** [comment]
Ok, thank you so much!
