### ISSUE TITLE
ld: can't map file, errno=22 file 'ft_countdown' for architecture arm64

### ISSUE THREAD

**Issue by vessfils** [JCluzet/42_EXAM#37]
Hello,

it seems there is an issue with clang, you can find the message from the trace. The exercise always failed:
ld: can't map file, errno=22 file 'ft_countdown' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

@JCluzet

**Comment by JCluzet** [comment]
Hi bladders 👋

First of all, thank you for using 42_EXAM.
This problem does not seem to be related to the program itself.
I invite you to try these different solutions:

1. Delete the whole 42-EXAM folder and re-clone it using git clone command.
2. Try to compile the exercise yourself using clang, do you find a problem or not? 
3. If you are on a mac (I suppose you are using the Apple Silicon chip) check that XCode is up to date.

If after that you still have the same problem tell me.
