### ISSUE TITLE
[ExamRank02 lvl0 search_and_reaplace] - wrong directory name

### ISSUE THREAD

**Issue by alex63rm** [JCluzet/42_EXAM#40]
Hello, there is a mistake in level0, Grademe says to put the search_and_replace.c in the directory rendu/searchandreplace, but it gives a compilation error because it expects the directory rendu/search_and_replace.
Please find below a snapshot:
![image](https://user-images.githubusercontent.com/71467121/210071670-d7cf6792-dc5f-4ee1-bc71-5562a84e69cf.png)

**Comment by JCluzet** [comment]
Hi @alex63rm 👋

Thank you for using **42_EXAM**.
Indeed the name of the folder was not correct.
Thank you for your remark I have just modified that just now.

If you have other problems do not hesitate to publish a new issue :)
