### ISSUE TITLE
Windows line separation

### ISSUE THREAD

**Issue by Kek5chen** [JCluzet/42_EXAM#46]
When committing #43 i explicitly checked every file for file endings so that they all use the standard linux LF which is also compatible with Windows. After you did your commits @JCluzet all the file endings for the files you touched reverted back to CRLF which keeps throwing errors under linux making the project unusable. Here an example:
```
kx@zero:/ $ make
.system/launch.sh: line 2: $'\r': command not found
.system/launch.sh: line 49: syntax error near unexpected token `$'do\r''
'system/launch.sh: line 49: `    for i in "${spin[@]}"; do
make: *** [Makefile:15: all] Error 2
```

Please check your file formatting and change it to LF in whichever IDE or text editor you work.

I'll push a formatting PR soon.

**Comment by Kek5chen** [comment]
What is your opinion on just adding a .gitattributes file with `* text=auto`

[Check this resource for more information](https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings)

**Comment by JCluzet** [comment]
I just added it ✅
