### ISSUE TITLE
[Exam 03] Bug on get_next_line correction.

### ISSUE THREAD

**Issue by Kuninoto** [JCluzet/42_EXAM#48]
Hello there,
On exam03 simulation I came across a bug on get_next_line exercise correction where I was graded FAILURE, it has created a **test** file with a lot of text in it (supposedly to use get_next_line in it) but got an empty trace.
Thanks in advance!

**Comment by JCluzet** [comment]
Hi Kuninoto 👋

Indeed this is not normal, can you send me the repo of your exercise get_next_line so that I try to reproduce the error on my side? 
Thanks!

**Comment by Kuninoto** [comment]
Huuh... I don't think I'll be able to send you the exact code that produced that output because eventually I've used 42_EXAM again and it was wiped but it's quite the same that I've done on my repository [42_get_next_line](https://github.com/Kuninoto/42_get_next_line) 
 excluding the .h and the utils were on the get_next_line.c

**Comment by JCluzet** [comment]
I checked by myself and the result was **SUCCESS**.
I took the code that was on your Git repo, that is this one: [The Code I Test](https://user.grademe.fr/gnl.c), can you tell me if on your side it works well also with this one? Thanks a lot!

**Comment by Kuninoto** [comment]
Yep. SUCCESS. Don't know what happened at first. I'll keep an eye on other submissions from my colleagues and get back to you if anything goes wrong. Thanks again! :)
