### ISSUE TITLE
Error in Exam sector with Kali Linux

### ISSUE THREAD

**Issue by cuhlig42** [JCluzet/42_EXAM#51]
Hey i tried to use the Exam programm today and it started to install but i got new Erros. 
![error 6](https://user-images.githubusercontent.com/113346209/212182577-4c486c1c-9dd3-40c9-a3c9-886742a76dee.png)

**Comment by JCluzet** [comment]
Hi @cuhlig42 👋
Was the error fixed by doing a `sudo apt-get update`?

**Comment by cuhlig42** [comment]
Hey @JCluzet I did 
sudo apt-get update 
and after this
sudo apt-get install libreadline-dev
and this
sudo apt-get install g++-6
both installation worked only after updating :)

**Comment by JCluzet** [comment]
Thanks, I have modified the program that will do a `sudo apt-get update` before installing **readline**, this error will not happen again.
