### ISSUE TITLE
The points per exercise are wrong

### ISSUE THREAD

**Issue by Kek5chen** [JCluzet/42_EXAM#57]
The points in the following screenshot should all say 25 and sum up to 100. Instead they are the next sum.

<img width="545" alt="Screen Shot 2023-01-26 at 2 26 35 PM" src="https://user-images.githubusercontent.com/52585984/214847109-05054e00-dbe4-482c-ac34-0f5a67a8e607.png">

**Comment by JCluzet** [comment]
Hi @Kek5chen 👋🏼
The "for 50 potential points" indicates how much TOTAL XP the exercise will add to your final score. 

It could have been for each exercise individually, but the real 42 exam shows the same thing.

**Comment by Kek5chen** [comment]
The real exam shows each exercise points individually.

**Comment by JCluzet** [comment]
I just checked and finally you are right, sorry! 
I'll change it as soon as possible. 
Thanks for the update :)

**Comment by JCluzet** [comment]
fix ✅
