### ISSUE TITLE
ft_range expected result

### ISSUE THREAD

**Issue by lubuper** [JCluzet/42_EXAM#62]
The expected result on ft_range was weird:

----------------8<-------------[ START TEST 
        💻 TEST
./a.out "3" "8"         🔎 YOUR OUTPUT:
3$
4$
5$
6$
7$
8$
        🗝 EXPECTED OUTPUT:
3$
4$
5$
6$
7$
8$
4113$
----------------8<------------- END TEST ]

**Comment by Ordajeannin** [comment]
Got the same error, and i tried to just put a "4113" at the end to pass the exercise.
But in a second test, ./a.out "1" "2", the expected output was... like expected

**Comment by Kuninoto** [comment]
This was in fact an error on the correction side,  thank you!
