### ISSUE TITLE
Contradictory subjects and tests

### ISSUE THREAD

**Issue by maplepy** [JCluzet/42_EXAM#63]
# Assignment name  : search_and_replace

> $>./search_and_replace "zaz" "art" "zul" | cat -e
$

> If the second argument is not contained in the first one (the string)
then the program simply rewrites the string followed by a newline.

then it should return `zaz` and not a new line

# Assignment name  : tab_mult

>  💻 TEST
>./a.out "12" "9"
>        🔎 YOUR OUTPUT:
>1 x 12 = 12$
>2 x 12 = 24$
>3 x 12 = 36$
>4 x 12 = 48$
>5 x 12 = 60$
>6 x 12 = 72$
>7 x 12 = 84$
>8 x 12 = 96$
>9 x 12 = 108$
>        🗝 EXPECTED OUTPUT:
>$

> If there are no parameters, the program displays \n.

Having **2 parameters** clearly means that **there are parameters** so it should not display a new line here either.

**Comment by Kuninoto** [comment]
These are in fact contradictory/wrong. I took the liberty to open a Pull Request in order to fix them. Thanks!
