### ISSUE TITLE
exam_rank02

### ISSUE THREAD

**Issue by PGCL1** [JCluzet/42_EXAM#75]
Hi, I hope you are doing good.

In the level 0 of exam rank02, the "search_and_replace" subject shows the following example outputs for the exercise:

Examples:
$>./search_and_replace "Papache est un sabre" "a" "o"
Popoche est un sobre
**$>./search_and_replace "zaz" "art" "zul" | cat -e
zaz$**
$>./search_and_replace "zaz" "r" "u" | cat -e
zaz$
$>./search_and_replace "jacob" "a" "b" "c" "e" | cat -e
$
$>./search_and_replace "ZoZ eT Dovid oiME le METol." "o" "a" | cat -e
ZaZ eT David aiME le METal.$
$>./search_and_replace "wNcOre Un ExEmPle Pas Facilw a Ecrirw " "w" "e" | cat -e
eNcOre Un ExEmPle Pas Facile a Ecrire $

I got the expected output but my exercise was marked as a fail.

➜  subjects git:(main) ✗ cd ../traces
➜  traces git:(main) ✗ cat 0-0_search_and_replace.trace
----------------8<-------------[ START TEST
        💻 TEST
./a.out "zaz" "art" "zul"
        🔎 YOUR OUTPUT:
zaz$
        🗝 EXPECTED OUTPUT:
$
----------------8<------------- END TEST ]

**Comment by jesuserr** [comment]
Hi, the subject is wrong, for that particular example it should say the following:

$>./search_and_replace "zaz" "art" "zul" | cat -e
$

**Comment by JCluzet** [comment]
fix with #82
