### ISSUE TITLE
Exam rank 05 accepts solutions that are not -Wall -Werror -Wextra proof

### ISSUE THREAD

**Issue by atchoglogilbert** [JCluzet/42_EXAM#80]

**Comment by JCluzet** [comment]
Hey @atchoglogilbert 👋🏼
The exercises in exam 05 are all compiled with the flags `-Wall -Werror -Wextra`. 
What error should there have been that you didn't get?
I'll try to reproduce it to understand on my end.

**Comment by atchoglogilbert** [comment]
Hi! Thanks for the reply! When I was practicing for the exam, I was passed even though I didn't compile my source code with the C flags, but the real exam kept giving me a fail ... or perhaps I'm mistaken. If you do check that the submitted code is CFLAGS proof, then you can just ignore the issue.

**Comment by JCluzet** [comment]
Yes, as you can see here [Tester ExamRank05](https://github.com/JCluzet/42_EXAM/blob/main/.subjects/STUD_PART/exam_05/1/cpp_module01/tester.sh) line 29, the exam is always compiled with the flags.
