### ISSUE TITLE
Exam Rank 02 exercice rostring

### ISSUE THREAD

**Issue by RowMax03** [JCluzet/42_EXAM#86]
<img width="804" alt="Bildschirm­foto 2023-04-25 um 22 09 40" src="https://user-images.githubusercontent.com/51720224/234391723-6acca219-b774-48d9-860d-a3ab30b4b7fc.png">
<img width="804" alt="Bildschirm­foto 2023-04-25 um 22 11 58" src="https://user-images.githubusercontent.com/51720224/234392040-9d2bed3e-c96d-45e0-9420-6d827f489e2c.png">
<img width="804" alt="Bildschirm­foto 2023-04-25 um 22 12 30" src="https://user-images.githubusercontent.com/51720224/234392046-371d32a5-ef98-48c3-8bcc-91ff45ab6b1f.png">
Am I stupid/missing smh or is the test broken?
<img width="438" alt="Bildschirm­foto 2023-04-25 um 22 13 31" src="https://user-images.githubusercontent.com/51720224/234392251-a6c02016-3fa3-4ecd-8a04-cc0601f5e8db.png">

**Comment by JCluzet** [comment]
Hi @RowMax03 👋
Thank you for your Issue.
The `$` displayed when you add `| cat -e` , displays an invisible character, here an `\n`.
As you can see in the traceback, you don't have this `$`, while the real version does. 
Didn't you just forget the ending `\n`?
Let me know
Good luck with your revisions!
