### ISSUE TITLE
Exam rank 04: no open fd test

### ISSUE THREAD

**Issue by SickMarco** [JCluzet/42_EXAM#87]
First of all, thank you for this great work. In the exam, in the multiple pipe test, the number of open fd is limited to 30. Moulinette uses $> ulimit -n 30; before running the test. The same (wrong) code passed the tester but failed the exam (my mistake, but I still managed to pass it : D )

**Comment by JCluzet** [comment]
Oh thank you for that comment, indeed I wasn't checking that. 
It is now fixed with the new push
Thanks again!
