### ISSUE TITLE
Empty rendu file returns success

### ISSUE THREAD

**Issue by mmtemel** [JCluzet/42_EXAM#88]
I have the success message when using the "grademe" command even though there is nothing in rendu. Because I didn't install clang. Except I have gcc. The output is:

```
waiting...
waiting...
waiting...
.system/grading/tester.sh: line 24: clang++: command not found
.system/grading/tester.sh: line 25: ./source: No such file or directory
rm: cannot remove 'source': No such file or directory

>>>>>>>>>> SUCCESS <<<<<<<<<<
```

Solved after installing clang.

**Comment by JCluzet** [comment]
Thank you for your issue.
I just fixed the problem with the last push which now checks that clang++, clang, gcc, g++ is installed before launching the program.
